[build]
  publish = "_site"
  command = "eleventy"

[[headers]]
#   Define which paths this specific [[headers]] block will cover.
  for = "/*"

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"